### ISSUE TITLE
In account creation, capture home location from drop down list

### ISSUE THREAD

**Issue by springframeworkguru** [Angular4JavaDevelopers/rfb-loyalty#1]
Need to set home location when user creates account. This will be used to default which location to display to user

**Comment by cfaddict** [comment]
This should be pretty easy to do for users that register but this might be tricky for users who log in with facebook or twitter. Any thoughts on that?

**Comment by springframeworkguru** [comment]
Can we after login, ask to set home location if not set?

**Comment by cfaddict** [comment]
What if we did something in the UI when they are setting their location for the first time. We can identify that they don't have a default location and ask them if they would like to set this as their default location.

**Comment by cfaddict** [comment]
I completed this but some issues came up with runners and users. I think I have solved them but this was just me not understanding the big picture of this app.
