### ISSUE TITLE
Social login doesn't create RfbUser

### ISSUE THREAD

**Issue by cfaddict** [Angular4JavaDevelopers/rfb-loyalty#19]
If we go with the current way we are doing things we are going to have a problem with the social login users. We need to create a RfbUsers for the first time these users log in.

**Comment by springframeworkguru** [comment]
We're good on this from out talk, right?

**Comment by springframeworkguru** [comment]
@cfaddict - Just pushed the refactoring of RFB User into user. I think this is what we needed.

**Comment by cfaddict** [comment]
We refactored RfbUser
