### ISSUE TITLE
Need default logged in screen to show event code entry

### ISSUE THREAD

**Issue by springframeworkguru** [Angular4JavaDevelopers/rfb-loyalty#4]
This will allow user to enter event code to prove attendance.

**Comment by cfaddict** [comment]
This goes back to the #6

**Comment by cfaddict** [comment]
I am not sure what you mean by this. When a runner logs in how would we show the event code? Who is getting the event code when they login?

**Comment by springframeworkguru** [comment]
Should be a form input for the event code. Runner gets the code from the organizer. 

Thought is to keep it simple for the runner, login, next screen should allow them to enter the event code. Since the code is unique, we don't even need to ask for the location. Keep it simple and easy to use. Make sense?
