### ISSUE TITLE
Setup Security Roles

### ISSUE THREAD

**Issue by springframeworkguru** [Angular4JavaDevelopers/rfb-loyalty#6]
Add security roles for Root, Admin, Organizer, Runner. Runner should be default role

**Comment by cfaddict** [comment]
I am working on the security roles setup and I just want to make sure I have this right. First off what is the root security role for? What would we need the ability to do that an admin couldn't? 

**Admin**
- Manage Users
- Manage Locations
- Manage Events
- Manage Event Attendance
- Manage Runners

**Organizer**
- Manage Events

**Runner**
- Logs event attendance (should be home page) 

Does this look right @springframeworkguru ?

**Comment by springframeworkguru** [comment]
Yes, that looks correct. In hindsight, I'm not sure if a root role is needed.

**Comment by cfaddict** [comment]
Awesome. Thanks, John!

**Comment by cfaddict** [comment]
I am deferring the runner's homepage to another issue. Other than that issue I have resolved all of the security issues.
