### ISSUE TITLE
Create UI Screens for Admin user

### ISSUE THREAD

**Issue by springframeworkguru** [Angular4JavaDevelopers/rfb-loyalty#7]
Need user maintenance to change user roles from runner, organizer, or Admin

Need to create, disable run locations can change run day of week.

**Comment by cfaddict** [comment]
If you log in with the current Admin role and go to user administration you can manage users from here. Will this be sufficient and will we need to make any changes to this? 

![2017-10-21_12-57-18](https://user-images.githubusercontent.com/349507/31853940-88670a2a-b65f-11e7-9418-541f98812261.png)

**Comment by cfaddict** [comment]
Looks like this is going to be enough for us.
