### ISSUE TITLE
Remove JHipster Branding, and RFB Branding to screens

### ISSUE THREAD

**Issue by springframeworkguru** [Angular4JavaDevelopers/rfb-loyalty#9]

**Comment by cfaddict** [comment]
This is a list of tasks I will complete for this issue.

- Remove JHipster logo
- Remove Name and version and replace with RFB logo
- the logo is black, change the background of navigation to white
- change color of menu items to black or something dark
- add leaderboard (done in a separate issue)
- add home page content, still working on what that is going to be

**Comment by cfaddict** [comment]
I think I will take a branch when I get to this point so that we can use this as an exercise for students. Here are the given tasks for this issue, go complete them and then I will show them what I did in the exercise review.

**Comment by springframeworkguru** [comment]
Sounds good!

**Comment by cfaddict** [comment]
I have this done but not done. I just have some filler text on the home page. 

@springframeworkguru Do you know what we want to put here?
